### ISSUE TITLE
Deal with the mysterious chin

### ISSUE THREAD

**Issue by berithpy** [genba-games/morsemadness#29]
For some reason the maze generator dies when you shrink the canvas. I'm looking into it and it dies when the maze generator is setting the corner down right to the wall.
Another thing i realized is that it does not happen if you set the y offset to 0.
The first question that comes to my mind is why do we deal with offsets instead of absolutes?
I'm still looking into it using this issue as a log!

**Comment by berithpy** [comment]
Nevermind my question, the offset acts like x and y coordinates!

**Comment by AlejoAsd** [comment]
The bottom and top edges are quite the hacks. I would not be surprised if
the bottom row is writing out of the array bounds.

**Comment by berithpy** [comment]
The chin has been dealt with in the 629219 commit.
